import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Navigator from "@/src/components/navigator";
import { Metadata } from "next";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Vanguard Lodge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cormorant.className} suppressHydrationWarning>
        {children}
        <Navigator />
      </body>
    </html>
  );
}
